# IMPORT LIBRARY

In [2]:
import numpy as np

from sklearn import neighbors, datasets #for input data
from sklearn.model_selection import train_test_split #for splitting data
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix #for evaluating results

from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import MinMaxScaler # min-max nomalization

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression #for Logistic Regression
from sklearn.svm import SVC #for SVM

import pandas as pd #for .csv, .xlxs 

# LOAD THE DATASET

In [3]:
heart_disease = pd.read_csv("cleveland-heart.csv")
heart_disease

a  b  c    d    e  f  g    h  j    s  k  l  m  num
0    63  1  1  145  233  1  2  150  0  2.3  3  0  6    0
1    67  1  4  160  286  0  2  108  1  1.5  2  3  3    1
2    67  1  4  120  229  0  2  129  1  2.6  2  2  7    1
3    37  1  3  130  250  0  0  187  0  3.5  3  0  3    0
4    41  0  2  130  204  0  2  172  0  1.4  1  0  3    0
..   .. .. ..  ...  ... .. ..  ... ..  ... .. .. ..  ...
586  48  0  2   -9  308  0  1   -9 -9  2.0  1 -9 -9    0
587  36  1  2  120  166  0  0  180  0  0.0 -9 -9 -9    0
588  48  1  3  110  211  0  0  138  0  0.0 -9 -9  6    0
589  47  0  2  140  257  0  0  135  0  1.0  1 -9 -9    0
590  53  1  4  130  182  0  0  148  0  0.0 -9 -9 -9    0

[591 rows x 14 columns]

In [4]:
#CHECK KIND OF SPECIES

heart_disease['num'].unique()

array([0, 1], dtype=int64)

In [5]:
#FROM SK.PREPROCESSING IMPORT LABELENCODER

#encode the species
num = [0, 1]
le = LabelEncoder()
le.fit(num)
heart_disease['num'] = le.fit_transform(heart_disease['num'].astype(str))

heart_disease

a  b  c    d    e  f  g    h  j    s  k  l  m  num
0    63  1  1  145  233  1  2  150  0  2.3  3  0  6    0
1    67  1  4  160  286  0  2  108  1  1.5  2  3  3    1
2    67  1  4  120  229  0  2  129  1  2.6  2  2  7    1
3    37  1  3  130  250  0  0  187  0  3.5  3  0  3    0
4    41  0  2  130  204  0  2  172  0  1.4  1  0  3    0
..   .. .. ..  ...  ... .. ..  ... ..  ... .. .. ..  ...
586  48  0  2   -9  308  0  1   -9 -9  2.0  1 -9 -9    0
587  36  1  2  120  166  0  0  180  0  0.0 -9 -9 -9    0
588  48  1  3  110  211  0  0  138  0  0.0 -9 -9  6    0
589  47  0  2  140  257  0  0  135  0  1.0  1 -9 -9    0
590  53  1  4  130  182  0  0  148  0  0.0 -9 -9 -9    0

[591 rows x 14 columns]

In [6]:
#FEATURES

heart_disease_X = heart_disease.drop('num', axis = 1)
heart_disease_X
#drop the last column aka num column into a single column

a  b  c    d    e  f  g    h  j    s  k  l  m
0    63  1  1  145  233  1  2  150  0  2.3  3  0  6
1    67  1  4  160  286  0  2  108  1  1.5  2  3  3
2    67  1  4  120  229  0  2  129  1  2.6  2  2  7
3    37  1  3  130  250  0  0  187  0  3.5  3  0  3
4    41  0  2  130  204  0  2  172  0  1.4  1  0  3
..   .. .. ..  ...  ... .. ..  ... ..  ... .. .. ..
586  48  0  2   -9  308  0  1   -9 -9  2.0  1 -9 -9
587  36  1  2  120  166  0  0  180  0  0.0 -9 -9 -9
588  48  1  3  110  211  0  0  138  0  0.0 -9 -9  6
589  47  0  2  140  257  0  0  135  0  1.0  1 -9 -9
590  53  1  4  130  182  0  0  148  0  0.0 -9 -9 -9

[591 rows x 13 columns]

In [7]:
#label, target, groundtruth

heart_disease_y = heart_disease['num'] #column y is the last column in dataset with the name num
heart_disease_y

0      0
1      1
2      1
3      0
4      0
      ..
586    0
587    0
588    0
589    0
590    0
Name: num, Length: 591, dtype: int32

# SPLIT DATA

In [8]:
# SPLIT DATA
from sklearn.model_selection import train_test_split # for splitting data 
# Split data into train set (80%), test set (20%)
# optional

X_train, X_test, y_train, y_test = train_test_split(heart_disease_X, heart_disease_y, test_size = 0.2, random_state = 0) #init parameters
print(X_train.shape) 
print(X_test.shape) 
print(y_train.shape) 
print(y_test.shape) 

(472, 13)
(119, 13)
(472,)
(119,)


# NORMALIZE DATA

In [9]:
# Check shape 

print(X_train.shape)
print(X_test.shape)

(472, 13)
(119, 13)


In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
#scaler

scaler.fit(X_train) #-> min, max of each column of X_train stored to "scaler"

C:\Users\VQ\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [12]:
#calculate and normalize X_train, X_test based on min, max of "scaler" --> range 0 -> 1

X_train_normalized = scaler.transform(X_train)
X_test_normalized = scaler.transform(X_test)
X_train_normalized

array([[0.04166667, 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.39583333, 1.        , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.625     , 1.        , 0.66666667, ..., 0.91666667, 0.55555556,
        0.9375    ],
       ...,
       [0.33333333, 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.79166667, 1.        , 1.        , ..., 0.91666667, 0.61111111,
        0.75      ],
       [0.52083333, 0.        , 0.33333333, ..., 0.83333333, 0.        ,
        0.        ]])

# LOGISTIC REGRESSION

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 100, random_state = 0)
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
model = model.fit(X_train_normalized, y_train)

C:\Users\VQ\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
y_test_pred = model.predict(X_test_normalized)
y_test_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1])

In [16]:
np.array(y_test)

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1])

In [17]:
from sklearn.metrics import accuracy_score

print('Test accuracy 1: ', model.score(X_test_normalized, y_test))
print('Test accuracy 2: ', accuracy_score(y_test, y_test_pred))

Test accuracy 1:  0.7815126050420168
Test accuracy 2:  0.7815126050420168


# CONFUSION MATRIX LOGISTIC REGRESSION

In [18]:
#CONFUSION MATRIX LOGISTIC REGRESSION
from sklearn.metrics import classification_report, confusion_matrix # for evaluating results
print("\tPREDICT\n\nACTUAL\n\n")
print("Confusion_matrix using Logistic Regression is  : ")
print(confusion_matrix(y_test, y_test_pred))
print("Classification_report using Logistic Regression is  : ")
print(classification_report(y_test, y_test_pred))

	PREDICT

ACTUAL


Confusion_matrix using Logistic Regression is  : 
[[54  8]
 [18 39]]
Classification_report using Logistic Regression is  : 
              precision    recall  f1-score   support

           0       0.75      0.87      0.81        62
           1       0.83      0.68      0.75        57

   micro avg       0.78      0.78      0.78       119
   macro avg       0.79      0.78      0.78       119
weighted avg       0.79      0.78      0.78       119



# SVM

In [19]:
model_svm = SVC(gamma='auto', kernel='linear', max_iter = 100) #C = ???
#model_svm = SVC(gamma='auto', kernel='poly', max_iter = 10)
#model_svm = SVC(gamma='auto', kernel='rbf', max_iter = 5) #gaussian 
model_svm

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=100, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
model_svm = model_svm.fit(X_train_normalized, y_train)

C:\Users\VQ\Anaconda3\lib\site-packages\sklearn\svm\base.py:244: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


In [21]:
y_test_pred_svm = model_svm.predict(X_test_normalized)
y_test_pred_svm

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1])

In [22]:
np.array(y_test)

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1])

In [23]:
print("Test accuracy 1: ", model_svm.score(X_test_normalized, y_test))
print("Test accuracy 2: ", accuracy_score(y_test, y_test_pred_svm))

Test accuracy 1:  0.7310924369747899
Test accuracy 2:  0.7310924369747899


In [24]:
cp = classification_report(y_test, y_test_pred_svm, output_dict=True)
cp

{'0': {'precision': 0.8,
  'recall': 0.6451612903225806,
  'f1-score': 0.7142857142857142,
  'support': 62},
 '1': {'precision': 0.6811594202898551,
  'recall': 0.8245614035087719,
  'f1-score': 0.746031746031746,
  'support': 57},
 'micro avg': {'precision': 0.7310924369747899,
  'recall': 0.7310924369747899,
  'f1-score': 0.7310924369747899,
  'support': 119},
 'macro avg': {'precision': 0.7405797101449276,
  'recall': 0.7348613469156763,
  'f1-score': 0.7301587301587301,
  'support': 119},
 'weighted avg': {'precision': 0.7430763609791743,
  'recall': 0.7310924369747899,
  'f1-score': 0.7294917967186874,
  'support': 119}}

# CONFUSION MATRIX SVM

In [25]:
#CONFUSION MATRIX SVM
print("\tPREDICT\n\nACTUAL\n\n")
print("Confusion_matrix using LINEAR SVM is  : ")
print(confusion_matrix(y_test, y_test_pred_svm, labels=[0, 1]))
print("Classification_report using LINEAR SVM is  : ")
print(classification_report(y_test, y_test_pred_svm))

	PREDICT

ACTUAL


Confusion_matrix using LINEAR SVM is  : 
[[40 22]
 [10 47]]
Classification_report using LINEAR SVM is  : 
              precision    recall  f1-score   support

           0       0.80      0.65      0.71        62
           1       0.68      0.82      0.75        57

   micro avg       0.73      0.73      0.73       119
   macro avg       0.74      0.73      0.73       119
weighted avg       0.74      0.73      0.73       119

